Refactor/button to a
teamrocketz/hault-chrome-extension pull request #15
Opened 2017-06-03 21:39 UTC by dwgate

No '_blank' when linking to our page.

2017-06-03 21:56 UTC, jhogan4288 reviewed
Minor:  `Date.now()` is a bit shorter & clearer than `new Date().getTime()`
Maybe add `!tab.url.match('about://')`?

2017-06-05 21:38 UTC, tonycassara approved these changes

2017-06-05 21:39 UTC, tonycassara requested changes
Please rebase, resolve conflicts.

2017-06-05 21:41 UTC, tonycassara approved these changes

2017-06-05 21:41 UTC, merged